<?php 
// phpcs:ignoreFile WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
// phpcs:ignoreFile WordPress.WP.AlternativeFunctions.file_system_operations_fwrite
// phpcs:ignoreFile WordPress.WP.AlternativeFunctions.file_system_operations_fclose
// phpcs:ignoreFile WordPress.WP.AlternativeFunctions.file_system_operations_fopen
// phpcs:ignoreFile WordPress.Security.EscapeOutput.ExceptionNotEscaped            

/**
 * EpsApiMyApi2WebModelsShipmentSpecificDeliveryFeatureModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PPLCZCPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CPL
 *
 * **Changelog**    * 2024-08-22 - SPRJ-13791 - validace PRTE / PRBC externích čísel - nelze použít najednou    - /shipment/batch    * 2024-07-01 - SPRJ-13838 - přidání    - /customer/address    * 2023-11-23 - SPRJ-12703 - CPL - /shipment - timestamp    - /shipment - Rozšíření výstupu o LastUpdateDate.    * 2023-07-13 - SPRJ-11888 - přidání    - /codelist/status - číselník statusů    * 2023-07-13 - SPRJ-11953 - přidání    - /order/cancel - storno objednávky
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PPLCZCPL\Model;

use \ArrayAccess;
use \PPLCZCPL\ObjectSerializer;

/**
 * EpsApiMyApi2WebModelsShipmentSpecificDeliveryFeatureModel Class Doc Comment
 *
 * @category Class
 * @description SpecificDeliveryFeatureModel
 * @package  PPLCZCPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EpsApiMyApi2WebModelsShipmentSpecificDeliveryFeatureModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Eps.Api.MyApi2.Web.Models.Shipment.SpecificDeliveryFeatureModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'specific_delivery_date' => '\DateTime',
        'specific_delivery_time_from' => 'string',
        'specific_delivery_time_to' => 'string',
        'specific_take_date' => '\DateTime',
        'specific_take_time_from' => 'string',
        'specific_take_time_to' => 'string',
        'access_point_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'specific_delivery_date' => 'date-time',
        'specific_delivery_time_from' => 'date-span',
        'specific_delivery_time_to' => 'date-span',
        'specific_take_date' => 'date-time',
        'specific_take_time_from' => 'date-span',
        'specific_take_time_to' => 'date-span',
        'access_point_code' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'specific_delivery_date' => 'specificDeliveryDate',
        'specific_delivery_time_from' => 'specificDeliveryTimeFrom',
        'specific_delivery_time_to' => 'specificDeliveryTimeTo',
        'specific_take_date' => 'specificTakeDate',
        'specific_take_time_from' => 'specificTakeTimeFrom',
        'specific_take_time_to' => 'specificTakeTimeTo',
        'access_point_code' => 'accessPointCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'specific_delivery_date' => 'setSpecificDeliveryDate',
        'specific_delivery_time_from' => 'setSpecificDeliveryTimeFrom',
        'specific_delivery_time_to' => 'setSpecificDeliveryTimeTo',
        'specific_take_date' => 'setSpecificTakeDate',
        'specific_take_time_from' => 'setSpecificTakeTimeFrom',
        'specific_take_time_to' => 'setSpecificTakeTimeTo',
        'access_point_code' => 'setAccessPointCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'specific_delivery_date' => 'getSpecificDeliveryDate',
        'specific_delivery_time_from' => 'getSpecificDeliveryTimeFrom',
        'specific_delivery_time_to' => 'getSpecificDeliveryTimeTo',
        'specific_take_date' => 'getSpecificTakeDate',
        'specific_take_time_from' => 'getSpecificTakeTimeFrom',
        'specific_take_time_to' => 'getSpecificTakeTimeTo',
        'access_point_code' => 'getAccessPointCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['specific_delivery_date'] = $data['specific_delivery_date'] ?? null;
        $this->container['specific_delivery_time_from'] = $data['specific_delivery_time_from'] ?? null;
        $this->container['specific_delivery_time_to'] = $data['specific_delivery_time_to'] ?? null;
        $this->container['specific_take_date'] = $data['specific_take_date'] ?? null;
        $this->container['specific_take_time_from'] = $data['specific_take_time_from'] ?? null;
        $this->container['specific_take_time_to'] = $data['specific_take_time_to'] ?? null;
        $this->container['access_point_code'] = $data['access_point_code'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets specific_delivery_date
     *
     * @return \DateTime|null
     */
    public function getSpecificDeliveryDate()
    {
        return $this->container['specific_delivery_date'];
    }

    /**
     * Sets specific_delivery_date
     *
     * @param \DateTime|null $specific_delivery_date SpecificDeliveryDate
     *
     * @return self
     */
    public function setSpecificDeliveryDate($specific_delivery_date)
    {
        $this->container['specific_delivery_date'] = $specific_delivery_date;

        return $this;
    }

    /**
     * Gets specific_delivery_time_from
     *
     * @return string|null
     */
    public function getSpecificDeliveryTimeFrom()
    {
        return $this->container['specific_delivery_time_from'];
    }

    /**
     * Sets specific_delivery_time_from
     *
     * @param string|null $specific_delivery_time_from SpecificDeliveryTimeFrom
     *
     * @return self
     */
    public function setSpecificDeliveryTimeFrom($specific_delivery_time_from)
    {
        $this->container['specific_delivery_time_from'] = $specific_delivery_time_from;

        return $this;
    }

    /**
     * Gets specific_delivery_time_to
     *
     * @return string|null
     */
    public function getSpecificDeliveryTimeTo()
    {
        return $this->container['specific_delivery_time_to'];
    }

    /**
     * Sets specific_delivery_time_to
     *
     * @param string|null $specific_delivery_time_to SpecificDeliveryTimeTo
     *
     * @return self
     */
    public function setSpecificDeliveryTimeTo($specific_delivery_time_to)
    {
        $this->container['specific_delivery_time_to'] = $specific_delivery_time_to;

        return $this;
    }

    /**
     * Gets specific_take_date
     *
     * @return \DateTime|null
     */
    public function getSpecificTakeDate()
    {
        return $this->container['specific_take_date'];
    }

    /**
     * Sets specific_take_date
     *
     * @param \DateTime|null $specific_take_date SpecificTakeDate
     *
     * @return self
     */
    public function setSpecificTakeDate($specific_take_date)
    {
        $this->container['specific_take_date'] = $specific_take_date;

        return $this;
    }

    /**
     * Gets specific_take_time_from
     *
     * @return string|null
     */
    public function getSpecificTakeTimeFrom()
    {
        return $this->container['specific_take_time_from'];
    }

    /**
     * Sets specific_take_time_from
     *
     * @param string|null $specific_take_time_from SpecificTakeTimeFrom
     *
     * @return self
     */
    public function setSpecificTakeTimeFrom($specific_take_time_from)
    {
        $this->container['specific_take_time_from'] = $specific_take_time_from;

        return $this;
    }

    /**
     * Gets specific_take_time_to
     *
     * @return string|null
     */
    public function getSpecificTakeTimeTo()
    {
        return $this->container['specific_take_time_to'];
    }

    /**
     * Sets specific_take_time_to
     *
     * @param string|null $specific_take_time_to SpecificTakeTimeTo
     *
     * @return self
     */
    public function setSpecificTakeTimeTo($specific_take_time_to)
    {
        $this->container['specific_take_time_to'] = $specific_take_time_to;

        return $this;
    }

    /**
     * Gets access_point_code
     *
     * @return string|null
     */
    public function getAccessPointCode()
    {
        return $this->container['access_point_code'];
    }

    /**
     * Sets access_point_code
     *
     * @param string|null $access_point_code ParcelShopCode
     *
     * @return self
     */
    public function setAccessPointCode($access_point_code)
    {
        $this->container['access_point_code'] = $access_point_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializerPpl::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializerPpl::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializerPpl::sanitizeForSerialization($this));
    }
}


